# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - ready_for_review
      - reopened
    branches:
      - develop
      - main

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  check-backend:
    name: Check Backend
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: make build
        working-directory: backend

  # TODO build-frontend-web

  # TODO build-frontend-mobile

  parameters:
    name: Get Parameters
    runs-on: self-hosted
    outputs:
      stage: ${{ steps.stage.outputs.stage }}
    steps:
      - id: stage
        run: |
          case ${{ env.BRANCH_NAME }} in
            "main")
              echo "::set-output name=stage::prd"
              ;;
            "develop")
              echo "::set-output name=stage::dev"
              ;;
            *)
              echo "branch does not have a matching environment configured"
              exit 1
              ;;
          esac

  deploy:
    name: Deploy Backend
    runs-on: self-hosted
    needs:
      - check-backend
      - parameters
    env:
      AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
      AWS_DOMAIN_NAME: ${{ secrets.AWS_DOMAIN_NAME }}
      AWS_ACM_CERTIFICATE_ARN: ${{ secrets.AWS_ACM_CERTIFICATE_ARN }}
    steps:
      - run: |
          echo "deploying branch '${{ env.BRANCH_NAME }}' to '${{ needs.parameters.outputs.stage }}'"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn sst cdk diff --stage ${{ needs.parameters.outputs.stage }}
